version: '2'
services:
  django:
    build:
      context: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - /code/node_modules
      - /code/build